export const mockAPIResponse = {
  user: {
    member_uid: "ae49c135-8653-4cf3-b64a-6c3025548661",
    photo: null,
    user: {
      first_name: "hoc",
      last_name: "admin",
      username: "admin",
      email: "houseofcharity97@gmail.com",
    },
    phone_number: "7990403421",
    profession: "software engineer",
    organization: "Turing",
    role: "ameer",
    enabled: true,
    address: {
      street: "A-126/4, Near Ashraf Masjid, Shaheen bagh,Okhla",
      locality: "Jamia Nagar",
      pincode: 110025,
      zone: null,
      city: 142,
    },
  },
  createdCases: [
    {
      case_uid: "c539c90c-f330-4774-b2a2-89cde6b52cc5",
      name: "sample case",
      description: "This is test",
      bank_account_name: "Mohd Areeb Javed",
      phone_number: "7990403421",
      email: "",
      location: "New Delhi",
      qr_code: "",
      upi_id: "",
      account_number: "1945273399",
      ifsc_code: "KKBK0000401",
      bank_name: "Kotak Mahindra Bank",
      zakat_eligible: true,
      created_by: 1,
      verification_document: "",
      required_amount: 5000,
      target_amount: 5000,
      assignee: {
        member_uid: "8a1bab66-8470-4345-8b97-edf4eada8fcd",
        photo: null,
        user: {
          first_name: "Areeb",
          last_name: "Javed",
          username: "maj",
          email: "mhdarb@gmail.com",
        },
        phone_number: "7990403421",
        profession: "Software engineer",
        organization: "Turing",
        role: "member",
        enabled: true,
        address: {
          street: "A-126/4, Near Ashraf Masjid, Shaheen bagh,Okhla",
          locality: "Jamia Nagar",
          pincode: 110025,
          zone: null,
          city: 142,
        },
      },
      latest_status: "ACTIVE",
      created_at: "2025-03-22T08:23:46.568639Z",
      updated_at: "2025-04-06T09:17:50.844152Z",
    },
    {
      case_uid: "08c185e7-24dc-4e4e-98f2-48693d1ff719",
      name: "Dummycase",
      description: "To understand the app setup",
      bank_account_name: "12345678910",
      phone_number: "9987105249",
      email: "",
      location: "Lucknow",
      qr_code: "",
      upi_id: "Erkamranullah@okicici",
      account_number: "",
      ifsc_code: "",
      bank_name: "",
      zakat_eligible: true,
      created_by: 1,
      verification_document: "",
      required_amount: 500,
      target_amount: 450,
      assignee: {
        member_uid: "ae49c135-8653-4cf3-b64a-6c3025548661",
        photo: null,
        user: {
          first_name: "hoc",
          last_name: "admin",
          username: "admin",
          email: "houseofcharity97@gmail.com",
        },
        phone_number: "7990403421",
        profession: "software engineer",
        organization: "Turing",
        role: "ameer",
        enabled: true,
        address: {
          street: "A-126/4, Near Ashraf Masjid, Shaheen bagh,Okhla",
          locality: "Jamia Nagar",
          pincode: 110025,
          zone: null,
          city: 142,
        },
      },
      latest_status: "CLOSED",
      created_at: "2025-03-23T11:17:52.837788Z",
      updated_at: "2025-03-26T13:57:55.834035Z",
    },
    {
      case_uid: "4b719287-9add-41d8-ae12-2e20fe68556f",
      name: "Sample Case 2",
      description: "Th8s is test",
      bank_account_name: "Mohd Areeb",
      phone_number: "7990403421",
      email: "",
      location: "",
      qr_code:
        "https://fkmqewzihfisvaywiteu.supabase.co/storage/v1/object/public/hocdocs/20250328233336_IMG-20250325-WA0015.jpg?",
      upi_id: "7990403421@paytm",
      account_number: "",
      ifsc_code: "",
      bank_name: "",
      zakat_eligible: true,
      created_by: 1,
      verification_document: "",
      required_amount: 5000,
      target_amount: 5000,
      assignee: {
        member_uid: "8a1bab66-8470-4345-8b97-edf4eada8fcd",
        photo: null,
        user: {
          first_name: "Areeb",
          last_name: "Javed",
          username: "maj",
          email: "mhdarb@gmail.com",
        },
        phone_number: "7990403421",
        profession: "Software engineer",
        organization: "Turing",
        role: "member",
        enabled: true,
        address: {
          street: "A-126/4, Near Ashraf Masjid, Shaheen bagh,Okhla",
          locality: "Jamia Nagar",
          pincode: 110025,
          zone: null,
          city: 142,
        },
      },
      latest_status: "CLOSED",
      created_at: "2025-03-28T18:03:37.802981Z",
      updated_at: "2025-03-29T15:53:03.932673Z",
    },
    {
      case_uid: "d3708ecf-9367-415c-9527-93483ab6b0cc",
      name: "Case 1 for April",
      description:
        "Assalamualaikum everyone,\r\n\r\nI am sharing my first case with the group since joining HOC in 2020.\r\n\r\nMohd. Bashir Ahmed sahab, the imam of a small masjid in Iradat Nagar, Bawana, has reached out to us for support. I used to offer namaz at his masjid during 2021 and 2022. He belongs to Linpur village near Ali Nagar, Darbhanga, and is the sole breadwinner for his family.\r\n\r\nHe has requested our assistance in arranging funds for his sister’s marriage, which is scheduled to take place between Eid-ul-Adha and Muharram. His financial condition is very limited, and I sincerely believe it is our responsibility to come forward and support him in this noble cause.\r\n\r\nI request our Amir sb to kindly set a generous target amount for this case. It is also eligible for Zakaat.\r\n\r\nJazakum Allahu Khairan.\r\n\r\nRegards,\r\nTabish Jamal Hashmi\r\nB.Tech (Civil), 2015 - JMI",
      bank_account_name: "QR SHARED BELOW",
      phone_number: "9987105249",
      email: "",
      location: "Delhi",
      qr_code:
        "https://fkmqewzihfisvaywiteu.supabase.co/storage/v1/object/public/hocdocs/20250407233944_IMG-20250407-WA0009.jpg?",
      upi_id: "",
      account_number: "",
      ifsc_code: "",
      bank_name: "",
      zakat_eligible: true,
      created_by: 1,
      verification_document: "",
      required_amount: 5000,
      target_amount: 5000,
      assignee: {
        member_uid: "2c63e7ae-0042-4fd9-b5b2-6cb2af65d9e4",
        photo: null,
        user: {
          first_name: "Ahad",
          last_name: "Noor",
          username: "P@ssw0rd",
          email: "ahad.1031@gmail.com",
        },
        phone_number: "9101247470",
        profession: "Teaching",
        organization: "PCE purnea",
        role: "member",
        enabled: true,
        address: {
          street: "Purnea",
          locality: "Purnea",
          pincode: 854301,
          zone: null,
          city: 160,
        },
      },
      latest_status: "ACTIVE",
      created_at: "2025-04-07T18:09:45.569071Z",
      updated_at: "2025-04-07T18:10:50.809315Z",
    },
  ],
  assignedCases: [
    {
      case_uid: "08c185e7-24dc-4e4e-98f2-48693d1ff719",
      name: "Dummycase",
      description: "To understand the app setup",
      bank_account_name: "12345678910",
      phone_number: "9987105249",
      email: "",
      location: "Lucknow",
      qr_code: "",
      upi_id: "Erkamranullah@okicici",
      account_number: "",
      ifsc_code: "",
      bank_name: "",
      zakat_eligible: true,
      created_by: 1,
      verification_document: "",
      required_amount: 500,
      target_amount: 450,
      assignee: {
        member_uid: "ae49c135-8653-4cf3-b64a-6c3025548661",
        photo: null,
        user: {
          first_name: "hoc",
          last_name: "admin",
          username: "admin",
          email: "houseofcharity97@gmail.com",
        },
        phone_number: "7990403421",
        profession: "software engineer",
        organization: "Turing",
        role: "ameer",
        enabled: true,
        address: {
          street: "A-126/4, Near Ashraf Masjid, Shaheen bagh,Okhla",
          locality: "Jamia Nagar",
          pincode: 110025,
          zone: null,
          city: 142,
        },
      },
      latest_status: "CLOSED",
      created_at: "2025-03-23T11:17:52.837788Z",
      updated_at: "2025-03-26T13:57:55.834035Z",
    },
  ],
  memberDonations: [
    {
      case_id: 1,
      case_name: "sample case",
      total_donated: 6068,
      donations: [
        {
          donation_reference_id: "506380861797",
          amount: 68,
          donated_at: "2025-03-04T19:21:00Z",
          is_verified: true,
          case_uid: "c539c90c-f330-4774-b2a2-89cde6b52cc5",
          verified_at: "2025-03-22T09:09:43.773067Z",
        },
        {
          donation_reference_id: "505463291208",
          amount: 3500,
          donated_at: "2025-02-23T12:54:00Z",
          is_verified: true,
          case_uid: "c539c90c-f330-4774-b2a2-89cde6b52cc5",
          verified_at: "2025-03-22T08:50:44.186878Z",
        },
        {
          donation_reference_id: "506271504911",
          amount: 1000,
          donated_at: "2025-03-03T16:21:00Z",
          is_verified: true,
          case_uid: "c539c90c-f330-4774-b2a2-89cde6b52cc5",
          verified_at: "2025-03-23T15:44:31.880783Z",
        },
        {
          donation_reference_id: "464638891326",
          amount: 300,
          donated_at: "2024-10-06T14:21:00Z",
          is_verified: true,
          case_uid: "c539c90c-f330-4774-b2a2-89cde6b52cc5",
          verified_at: "2025-03-23T15:46:45.591499Z",
        },
        {
          donation_reference_id: "432583286381",
          amount: 1200,
          donated_at: "2024-11-20T19:00:00Z",
          is_verified: true,
          case_uid: "c539c90c-f330-4774-b2a2-89cde6b52cc5",
          verified_at: "2025-03-23T15:44:43.703999Z",
        },
      ],
    },
    {
      case_id: 2,
      case_name: "Dummycase",
      total_donated: 4830,
      donations: [
        {
          donation_reference_id: "508223300895",
          amount: 50,
          donated_at: "2025-03-24T05:07:30.016539Z",
          is_verified: false,
          case_uid: "08c185e7-24dc-4e4e-98f2-48693d1ff719",
        },
        {
          donation_reference_id: "422613267424",
          amount: 2500,
          donated_at: "2025-03-25T12:07:50.500998Z",
          is_verified: false,
          case_uid: "08c185e7-24dc-4e4e-98f2-48693d1ff719",
        },
        {
          donation_reference_id: "310520558400",
          amount: 1500,
          donated_at: "2023-04-15T15:26:00Z",
          is_verified: false,
          case_uid: "08c185e7-24dc-4e4e-98f2-48693d1ff719",
        },
        {
          donation_reference_id: "508449024539",
          amount: 725,
          donated_at: "2025-03-25T14:06:00Z",
          is_verified: true,
          case_uid: "08c185e7-24dc-4e4e-98f2-48693d1ff719",
          verified_at: "2025-03-26T13:57:55.849147Z",
        },
        {
          donation_reference_id: "545052388026",
          amount: 55,
          donated_at: "2025-03-25T14:00:00Z",
          is_verified: false,
          case_uid: "08c185e7-24dc-4e4e-98f2-48693d1ff719",
        },
      ],
    },
    {
      case_id: 5,
      case_name: "Case 1 for April",
      total_donated: 1000,
      donations: [
        {
          donation_reference_id: "546358992821",
          amount: 1000,
          donated_at: "2025-04-07T23:46:31.655516Z",
          is_verified: true,
          case_uid: "d3708ecf-9367-415c-9527-93483ab6b0cc",
          verified_at: "2025-04-07T18:16:40.162611Z",
        },
      ],
    },
  ],
  membersList: [
    {
      member_uid: "36833500-2296-4e40-a5af-de2df185fa26",
      photo: null,
      user: {
        first_name: "Abdul",
        last_name: "Kadir",
        username: "AQADIR",
        email: "abdulqadir.jmi10@gmail.com",
      },
      phone_number: "7088333381",
      profession: "Manager",
      organization: "INDIAN OIL CORPORATIONLIMITEDT",
      role: "member",
      enabled: true,
      address: {
        street: "NORTHRN REGIONPIPELINSE",
        locality: "Presently in Bhubaneswar",
        pincode: 754141,
        zone: null,
        city: 38,
      },
    },
    {
      member_uid: "2c63e7ae-0042-4fd9-b5b2-6cb2af65d9e4",
      photo: null,
      user: {
        first_name: "Ahad",
        last_name: "Noor",
        username: "P@ssw0rd",
        email: "ahad.1031@gmail.com",
      },
      phone_number: "9101247470",
      profession: "Teaching",
      organization: "PCE purnea",
      role: "member",
      enabled: true,
      address: {
        street: "Purnea",
        locality: "Purnea",
        pincode: 854301,
        zone: null,
        city: 160,
      },
    },
    {
      member_uid: "092d05f4-7142-4ab6-8b36-489610d9b87c",
      photo: null,
      user: {
        first_name: "Ahmad",
        last_name: "omar",
        username: "bahjatfrequent@gmail.com",
        email: "bahjatfrequent@gmail.com",
      },
      phone_number: "8291529531",
      profession: "Engineer",
      organization: "TVS",
      role: "member",
      enabled: true,
      address: {
        street: "",
        locality: "",
        pincode: null,
        zone: null,
        city: 51,
      },
    },
    {
      member_uid: "0b81f2c8-27ff-42f5-ba33-3bfa163f6d68",
      photo: null,
      user: {
        first_name: "Amaan",
        last_name: "Ullah",
        username: "Ullah.amaan@gmail.com",
        email: "ullah.amaan@gmail.com",
      },
      phone_number: "9971506933",
      profession: "IT Analyst",
      organization: "Telstra Health Australia",
      role: "member",
      enabled: true,
      address: {
        street: "Okhla Vihar",
        locality: "Jamia Nagar",
        pincode: 110025,
        zone: null,
        city: 142,
      },
    },
    {
      member_uid: "5ac2479d-5464-43a2-8a48-dc9f368e8892",
      photo: null,
      user: {
        first_name: "Ansar",
        last_name: "Qidwai",
        username: "ansarqidwai",
        email: "ansarqidwai@gmail.com",
      },
      phone_number: "9811337280",
      profession: "Business",
      organization: "Home Trends",
      role: "member",
      enabled: true,
      address: {
        street: "Iim road",
        locality: "Bhitoli",
        pincode: 226013,
        zone: null,
        city: 120,
      },
    },
    {
      member_uid: "8a1bab66-8470-4345-8b97-edf4eada8fcd",
      photo: null,
      user: {
        first_name: "Areeb",
        last_name: "Javed",
        username: "maj",
        email: "mhdarb@gmail.com",
      },
      phone_number: "7990403421",
      profession: "Software engineer",
      organization: "Turing",
      role: "member",
      enabled: true,
      address: {
        street: "A-126/4, Near Ashraf Masjid, Shaheen bagh,Okhla",
        locality: "Jamia Nagar",
        pincode: 110025,
        zone: null,
        city: 142,
      },
    },
    {
      member_uid: "d1044aa6-7703-4df9-a080-e4f3e329b9d6",
      photo: null,
      user: {
        first_name: "Bilal",
        last_name: "Ahmad",
        username: "mh3dbilal@gmail.com",
        email: "mh3dbilal@gmail.com",
      },
      phone_number: "8574747355",
      profession: "Software professional",
      organization: "Oracle",
      role: "member",
      enabled: true,
      address: {
        street: "Vikas Nagar sector 7",
        locality: "Vikas Nagar",
        pincode: 226022,
        zone: null,
        city: 120,
      },
    },
    {
      member_uid: "19b4d09a-1194-46bf-83be-8ef0c98356d4",
      photo: null,
      user: {
        first_name: "Ehteshamuddin",
        last_name: "Syed",
        username: "syedehtesham",
        email: "syedehteshamuddin71@gmail.com",
      },
      phone_number: "9290192150",
      profession: "Engineer",
      organization: "Nextracker",
      role: "member",
      enabled: true,
      address: {
        street: "",
        locality: "",
        pincode: null,
        zone: null,
        city: 88,
      },
    },
    {
      member_uid: "6bcd0fdb-8965-4505-b304-630f5bbdc9e9",
      photo: null,
      user: {
        first_name: "Faisal",
        last_name: "Khan",
        username: "faisal",
        email: "faisalshafiqkhan98@gmail.com",
      },
      phone_number: "8851048816",
      profession: "Project Manager",
      organization: "DXC Technology",
      role: "member",
      enabled: true,
      address: {
        street: "B - 105",
        locality: "Shaheen Bagh",
        pincode: 110025,
        zone: null,
        city: 142,
      },
    },
    {
      member_uid: "a9ba56bf-5547-4334-8dcf-f164e0d4de76",
      photo: null,
      user: {
        first_name: "Farhan",
        last_name: "Ashraf",
        username: "farhanashraf555@gmail.com",
        email: "farhanashraf555@gmail.com",
      },
      phone_number: "919654994493",
      profession: "Engineer",
      organization: "UPS Canada",
      role: "member",
      enabled: true,
      address: {
        street: "501 Huda Homes",
        locality: "Jamal Road",
        pincode: 800001,
        zone: null,
        city: 152,
      },
    },
    {
      member_uid: "23477913-e98b-4d5a-ae2e-7cc3c9ee4afa",
      photo: null,
      user: {
        first_name: "Harith",
        last_name: "Mohamed",
        username: "harry1496@gmail.com",
        email: "harry1496@gmail.com",
      },
      phone_number: "9381046188",
      profession: "Research scholar",
      organization: "IITM",
      role: "member",
      enabled: true,
      address: {
        street: "Shenoy nagar",
        locality: "Shenoy nagar",
        pincode: 600030,
        zone: null,
        city: 51,
      },
    },
    {
      member_uid: "ae49c135-8653-4cf3-b64a-6c3025548661",
      photo: "dummy",
      user: {
        first_name: "hoc",
        last_name: "admin",
        username: "admin",
        email: "houseofcharity97@gmail.com",
      },
      phone_number: "8920523536",
      profession: "software engineer",
      organization: "Turing",
      role: "ameer",
      enabled: true,
      address: {
        street: "A-126/4, Near Ashraf Masjid, Shaheen bagh,Okhla",
        locality: "Jamia Nagar",
        pincode: 110025,
        zone: null,
        city: 142,
      },
    },
    {
      member_uid: "383adaad-10ba-4eff-ae58-02ba41372940",
      photo: null,
      user: {
        first_name: "Kamran",
        last_name: "Khan",
        username: "Kamrankhan",
        email: "Kamrankhan.jmi@gmail.com",
      },
      phone_number: "9986103249",
      profession: "Mechanical engineer",
      organization: "General electric",
      role: "member",
      enabled: true,
      address: {
        street: "529ga/307",
        locality: "Kamla nehru nagar",
        pincode: 226022,
        zone: null,
        city: 120,
      },
    },
    {
      member_uid: "b70d8297-3acf-404b-ac29-c2e52cc0a7a6",
      photo: null,
      user: {
        first_name: "Meraj",
        last_name: "Ahmad",
        username: "meraj",
        email: "meraj025@gmail.com",
      },
      phone_number: "447587793521",
      profession: "Engineer",
      organization: "University of Glasgow",
      role: "member",
      enabled: true,
      address: {
        street: "",
        locality: "",
        pincode: null,
        zone: null,
        city: null,
      },
    },
    {
      member_uid: "f820a064-fc0d-4efc-928b-b0e5de0876ba",
      photo: null,
      user: {
        first_name: "Mohamed",
        last_name: "Jabir",
        username: "jabir.sait93@gmail.com",
        email: "jabir.sait93@gmail.com",
      },
      phone_number: "8281725459",
      profession: "Engineer",
      organization: "Qualcomm",
      role: "member",
      enabled: true,
      address: {
        street: "",
        locality: "",
        pincode: 560067,
        zone: null,
        city: 27,
      },
    },
    {
      member_uid: "d852d65a-0b95-4133-ae5b-ba156aa79bc3",
      photo: null,
      user: {
        first_name: "Mohammad Khurram",
        last_name: "Ali",
        username: "khurram32",
        email: "alimkhurram@gmail.com",
      },
      phone_number: "7011283112",
      profession: "Salaried",
      organization: "AAI",
      role: "member",
      enabled: true,
      address: {
        street: "",
        locality: "",
        pincode: 110025,
        zone: null,
        city: 142,
      },
    },
    {
      member_uid: "a1d2b543-8073-498b-a795-d5e8a7e43662",
      photo: null,
      user: {
        first_name: "Mohammad Talha",
        last_name: "Javed",
        username: "mhdtlh",
        email: "mhdtlh@gmail.com",
      },
      phone_number: "9540253300",
      profession: "Manager",
      organization: "Escorts Kubota Ltd",
      role: "member",
      enabled: true,
      address: {
        street: "A-126/4, Near Ashraf Masjid",
        locality: "Shaheen Bagh, Jamia Nagar",
        pincode: 110025,
        zone: null,
        city: 142,
      },
    },
    {
      member_uid: "0589efe7-8573-4117-bfed-707e69644374",
      photo: null,
      user: {
        first_name: "Mohammed",
        last_name: "Najamuddin",
        username: "najamuddin7000@gmail.com",
        email: "najamuddin7000@gmail.com",
      },
      phone_number: "7674009617",
      profession: "Geotechnical Engineer",
      organization: "L&T Construction",
      role: "member",
      enabled: true,
      address: {
        street: "",
        locality: "Saidabad",
        pincode: 500059,
        zone: null,
        city: 88,
      },
    },
    {
      member_uid: "0f26d7e6-6dc5-4f87-99b8-fd8ac5a4210f",
      photo: null,
      user: {
        first_name: "Mohd",
        last_name: "Rizwan",
        username: "rizwanriders@gmail.com",
        email: "rizwanriders@gmail.com",
      },
      phone_number: "7710091913",
      profession: "Service",
      organization: "Psu",
      role: "member",
      enabled: true,
      address: {
        street: "",
        locality: "",
        pincode: 400074,
        zone: null,
        city: 131,
      },
    },
    {
      member_uid: "b4cd163e-b848-4c27-a4ae-ba5c925e715c",
      photo: null,
      user: {
        first_name: "Mohd",
        last_name: "Umar",
        username: "umar",
        email: "umarfaroquiiii@gmail.com",
      },
      phone_number: "7017087245",
      profession: "Student",
      organization: "JBIT COLLEGE OF APPLIED SCIENCE",
      role: "member",
      enabled: true,
      address: {
        street: "Kalalan Street",
        locality: "Nagina, distt bijnor",
        pincode: 246762,
        zone: null,
        city: 130,
      },
    },
    {
      member_uid: "49f53e47-92b1-4515-b133-a5a96c97987c",
      photo: null,
      user: {
        first_name: "MOHD",
        last_name: "AZHAR",
        username: "azharhoc",
        email: "6165mohdazhar@gmail.com",
      },
      phone_number: "9990894909",
      profession: "Engineer",
      organization: "Delhi Transco Ltd",
      role: "member",
      enabled: true,
      address: {
        street: "Kabir Nagar",
        locality: "Kabir Nagar",
        pincode: 110094,
        zone: null,
        city: 60,
      },
    },
    {
      member_uid: "c5b66f12-645f-40dc-8f85-3976fed9449c",
      photo: null,
      user: {
        first_name: "Mohd",
        last_name: "Zuhair",
        username: "zuhair.alig31@gmail.com",
        email: "zuhair.alig31@gmail.com",
      },
      phone_number: "6589314523",
      profession: "Researcher",
      organization: "NTU Singapore",
      role: "member",
      enabled: true,
      address: {
        street: "Baruzai First",
        locality: "Jurong East",
        pincode: 242001,
        zone: null,
        city: 59,
      },
    },
    {
      member_uid: "341a7520-9a67-4823-9616-361227072dd2",
      photo: null,
      user: {
        first_name: "Mohd",
        last_name: "Mushahid",
        username: "9810936460",
        email: "mohdmushahid9954@gmail.com",
      },
      phone_number: "9810936460",
      profession: "Engineering",
      organization: "Tata Consultancy services",
      role: "member",
      enabled: true,
      address: {
        street: "Seedhi Sarai, Near Sambhali Gate",
        locality: "Galshaheed",
        pincode: 244001,
        zone: null,
        city: 130,
      },
    },
    {
      member_uid: "e6cfa928-a016-4493-85cf-613589c1fb3b",
      photo: null,
      user: {
        first_name: "Nabeel",
        last_name: "",
        username: "nabeelali22@gmail.com",
        email: "nabeelali22@gmail.com",
      },
      phone_number: "9718869085",
      profession: "Consultant",
      organization: "Kaizen Institute",
      role: "member",
      enabled: true,
      address: {
        street: "8",
        locality: "Batla House",
        pincode: 110025,
        zone: null,
        city: 142,
      },
    },
    {
      member_uid: "36e586dc-eaf0-4054-80bd-eed2594f22ca",
      photo: null,
      user: {
        first_name: "Safique",
        last_name: "Anwer",
        username: "safiqueAnwer",
        email: "safiqueanwer@gmail.com",
      },
      phone_number: "8954979116",
      profession: "PhD Scholar",
      organization: "Khalifa University",
      role: "member",
      enabled: true,
      address: {
        street: "",
        locality: "",
        pincode: 841226,
        zone: null,
        city: 152,
      },
    },
    {
      member_uid: "23e1636d-2ad5-474b-a925-b71034c043cd",
      photo: null,
      user: {
        first_name: "Shahrukh",
        last_name: "Ahmed",
        username: "shahrukhahmedjmi@gmail.com",
        email: "shahrukhahmedjmi@gmail.com",
      },
      phone_number: "9899471473",
      profession: "Structural Engineer",
      organization: "L&T Construction",
      role: "member",
      enabled: true,
      address: {
        street: "Muglivakkam",
        locality: "Muglivakkam",
        pincode: 600116,
        zone: null,
        city: 51,
      },
    },
    {
      member_uid: "f9e947de-47dc-41da-ad69-9851fe888532",
      photo: null,
      user: {
        first_name: "Shazee",
        last_name: "Rahmani",
        username: "Shazee",
        email: "Shaziiitg@gmail.com",
      },
      phone_number: "8789940180",
      profession: "Teacher",
      organization: "Ajmal Super 40",
      role: "member",
      enabled: true,
      address: {
        street: "Azad Nagar",
        locality: "Araria",
        pincode: 854311,
        zone: null,
        city: 160,
      },
    },
    {
      member_uid: "fb7a7e35-1d73-4701-b5a5-19ac9260c9c6",
      photo: null,
      user: {
        first_name: "Sweet",
        last_name: "Fairy",
        username: "ismailsharief.b@gmail.com",
        email: "ismailsharief.b@gmail.com",
      },
      phone_number: "9902078331",
      profession: "IT",
      organization: "Happiest Minds Technologies",
      role: "member",
      enabled: true,
      address: {
        street: "Vishwanathapuram",
        locality: "Madurai",
        pincode: 625014,
        zone: null,
        city: 123,
      },
    },
    {
      member_uid: "f5051b16-72f3-4479-bead-7e66b57d52fe",
      photo: null,
      user: {
        first_name: "Syed Zaid",
        last_name: "Abdin",
        username: "zaidabdin",
        email: "zaidabdin97@gmail.com",
      },
      phone_number: "9718549392",
      profession: "Engineer",
      organization: "NLCIL",
      role: "member",
      enabled: true,
      address: {
        street: "NTPL TOWNSHIP",
        locality: "Harbour Estate",
        pincode: 628004,
        zone: null,
        city: 200,
      },
    },
    {
      member_uid: "1fcb95d3-b88c-46a1-a92b-12fefe871b4c",
      photo: null,
      user: {
        first_name: "Tabish",
        last_name: "Jamal Hashmi",
        username: "tjtabish@gmail.com",
        email: "tjtabish@gmail.com",
      },
      phone_number: "7503482724",
      profession: "Project Manager",
      organization: "Larsen and Toubro",
      role: "member",
      enabled: true,
      address: {
        street: "302, C-138, Sufia Apartment, Lane 4, Johri Farm, Jamia Nagar",
        locality: "Jamia Nagar",
        pincode: 110025,
        zone: null,
        city: 60,
      },
    },
    {
      member_uid: "369eb8f8-2034-4e52-ac11-5b8d9389c635",
      photo: null,
      user: {
        first_name: "The",
        last_name: "Un_Reluctant",
        username: "nooruzzaman1044@gmail.com",
        email: "nooruzzaman1044@gmail.com",
      },
      phone_number: "8210854353",
      profession: "PIPING LAYOUT ENGINEER",
      organization: "Bechtel India",
      role: "member",
      enabled: true,
      address: {
        street: "JASOLA VIHAR",
        locality: "Advocate compound",
        pincode: 110025,
        zone: null,
        city: 142,
      },
    },
    {
      member_uid: "e6d3b74b-7864-450d-ab71-a92f18360f9b",
      photo: null,
      user: {
        first_name: "Touseef",
        last_name: "Ahmed",
        username: "srmflats@gmail.com",
        email: "srmflats@gmail.com",
      },
      phone_number: "9870493044",
      profession: "Student",
      organization: "Al Falah",
      role: "member",
      enabled: true,
      address: {
        street: "45",
        locality: "Jamia",
        pincode: 110025,
        zone: null,
        city: 142,
      },
    },
  ],
};
